### ISSUE TITLE
GIR crashes generating vte-rs

### ISSUE THREAD

**Issue by Cogitri** [gtk-rs/gir#784]
Generating [vte-rs](https://github.com/Cogitri/vte-rs) fails:

```
thread 'main' panicked at 'get rust type from param: Ignored("glib::Pid")', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  10: libgir::analysis::bounds::Bounds::add_for_parameter
  11: libgir::analysis::functions::analyze_function
  12: libgir::analysis::functions::analyze
  13: libgir::analysis::object::class
  14: libgir::analysis::run
  15: gir::main
  16: std::rt::lang_start::{{closure}}
  17: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  19: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  20: main
  21: <unknown>
             at src/env/__libc_start_main.c:94
```

## Steps to reproduce:

1. Clone https://github.com/Cogitri/vte-rs
2. Uncomment `"Vte.Pty"` in Gir.toml
3. run `gir`

Tested with latest gir (f511aaeee8a324dc8d23b7a854121739b9bfcd2e)

**Comment by EPashkin** [comment]
Thanks for reporting.
Temporary solution: add `"GLib.Pid",` to `manual` array,
then `vte_terminal_watch_child` will normally generated.

**Comment by Cogitri** [comment]
Huh, somehow I thought I had already done that! Thanks, that works for now :)

**Comment by EPashkin** [comment]
I was wrong about problem function: actually it `vte_terminal_spawn_async` that also need manual  "GLib.SpawnFlags" and "Gio.Cancellable"

**Comment by Cogitri** [comment]
Yup, but it appears that SpawnFlags isn't a thing yet in glib-rs?

**Comment by EPashkin** [comment]
@Cogitri Yes, currently no "GLib.SpawnFlags" generated

**Comment by GuillaumeGomez** [comment]
In any case, it shouldn't crash. :)

**Comment by GuillaumeGomez** [comment]
@EPashkin Why did you close it btw?

**Comment by GuillaumeGomez** [comment]
Oh my bad, didn't see the linked PR. Nevermind! :-.
